sudo: required

services:
  - docker

before_install:
  - docker build -t siva/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run siva/react-test npm test -- --coverage 

after_success:
  - docker build -t siva/multi-client ./client
  - docker build -t siva/multi-server ./server
  - docker build -t siva/multi-nginx ./nginx
  - docker build -t siva/multi-worker ./worker

  # DockerLogin
 - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

  # push to docker hub
  - docker push siva/multi-client
  - docker push siva/multi-server
  - docker push siva/multi-nginx
  - docker push siva/multi-worker



